### ISSUE TITLE
Capture de la page entière et l'envoyer sur Pinterest

### ISSUE THREAD

**Issue by thvi** [AminaG/OpenScreenshot#17]
Bonjour,

http://bit.ly/1YqnnB5
Je ne parviens pas à envoyer une capture de la page Web sur Pinterest. Il faut que je m'y reprenne à deux reprises pour que cela fonctionne.

À part ce petit bug, vous avez développé un super outil pour les Designers :)
Merci !

Cordialement.

**Comment by dandv** [comment]
What's up with the French in [these issues](https://github.com/AminaG/OpenScreenshot/issues/41#issuecomment-253364241)?!

**Comment by AminaG** [comment]
You welcome to post translation

**Comment by dandv** [comment]
> You welcome to post translation

I won't do @thvi's work because that won't educate him or other users to use Google Translate and post in English.

By the way, [machine translation has reach near-human levels of accuracy](https://techcrunch.com/2016/09/27/google-unleashes-deep-learning-tech-on-language-with-neural-machine-translation/).

![image](https://cloud.githubusercontent.com/assets/33569/20250904/e06aa618-a9c8-11e6-9840-26c4cc73990f.png)
