### ISSUE TITLE
Missing LICENSE or COPYING

### ISSUE THREAD

**Issue by omouse** [AminaG/OpenScreenshot#23]
the license is missing, is this MIT or GPLv3 licensed?

**Comment by HenrikBengtsson** [comment]
:+1: 

Yes, please add explicit license statement.

**Comment by Jexah** [comment]
(Y)

**Comment by Jexah** [comment]
:+1:

**Comment by AminaG** [comment]
What license do you prefer?

**Comment by HenrikBengtsson** [comment]
Thanks.  Either GPL 3 or MIT would be great.

@AminaG, I'm not sure how familiar you are with software licenses and copyrights, but the copyright holder(s) can at anytime choose another license for upcoming versions.  What you cannot do is change the past, that is, as soon as you've released a version under a certain license you cannot the license for that version.  I'm saying this, because some people never get around to pick a license because they think they have to stick to it for the rest of life. The "only" thing you have to worry about who is holding the copyright and if you have contributors that have contributed enough to be considered copyright holders, you of course need to discuss with them.

**Comment by AminaG** [comment]
Thanks for the info.
What is the most important main difference between GPL 3 MIT and Apache?
What do you prefer and why?

**Comment by kesara** [comment]
[GitHub's choosealicense.com](http://choosealicense.com/) is a nice simple website which gives overview about which license to choose, depending on what you want.
If you want an advanced overview of open source license have a look at https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

I personally prefer GNU GPL v3. :)

**Comment by doronpt** [comment]
Hi AminaG,

Thanks for this great tool!

We are working on an internal tool that needs screen capturing abilities and want to adapt your code for this purpose.

However, our legal department is asking under which license your code is released. Are you able to publish it under one of the standard open source licenses? 
Adding such a license to your readme file would be great.

**Comment by omouse** [comment]
license/copying file is still missing, @doronpt at this point you may want to explore other options that have a GPL3 or LGPL or MIT license or ask your legal department what license they would assume (public domain may be a possibility but may present its own problems)

this is why it's still important to add a LICENSE or COPYING file to each and every project. I too would love to live in a world without software licenses where all code is assumed to be open source, but that's just not the world we live in unfortunately. Copyright laws care about you even if you don't care about them.

**Comment by AminaG** [comment]
I choose MIT.

**Comment by HenrikBengtsson** [comment]
:+1:
